jobs:
  run-bot:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # تشغيل 5 عمليات متوازية في نفس اللحظة (حسب المسموح)
        instance: [1, 2, 3, 4, 5]
    steps:
      - run: python main.py
